name: Azure Packer Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          curl -fsSL -o packer.zip https://releases.hashicorp.com/packer/1.15.0/packer_1.15.0_linux_amd64.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Run Packer Init
        run: packer init azure-ubuntu.pkr.hcl

      - name: Run Packer Validate
        run: |
          packer validate \
          -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
          azure-ubuntu.pkr.hcl

      - name: Run Packer Build
        run: |
          packer build \
          -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
          -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
          azure-ubuntu.pkr.hcl
