name: Packer Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  #push:
   # branches:
    #  - master

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2

          
      - name: Clean packer cache
        run: |
          rm -rf ~/.config/packer
          rm -rf ~/.packer.d

      - name: Show packer file
        run: cat aws-ubuntu.pkr.hcl

        
      

     

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2" # Optionally include this if you're using a specific region

      - name: Run Packer Build
        run: |
          packer init aws-ubuntu.pkr.hcl
          packer validate aws-ubuntu.pkr.hcl
          packer fmt aws-ubuntu.pkr.hcl
          packer build aws-ubuntu.pkr.hcl
