name: Packer Build Azure

on:
  pull_request:
    branches:
      - master

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          curl -fsSL -o packer.zip https://releases.hashicorp.com/packer/1.8.4/packer_1.8.4_linux_amd64.zip
          unzip packer.zip
          sudo mv packer /usr/local/bin/
          packer --version

      - name: Set Azure credentials as env vars
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: Run Packer Build
        run: |
          packer init azure-ubuntu.pkr.hcl
          packer validate azure-ubuntu.pkr.hcl
          packer fmt azure-ubuntu.pkr.hcl
          packer build azure-ubuntu.pkr.hcl
