name: Build AMI

on:
  push:
    branches:
      - master

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2

      - name: Setup Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Packer Init
        working-directory: ansible
        run: packer init .

      - name: Packer Validate
        working-directory: ansible
        run: packer validate .

      - name: Packer Build
        working-directory: ansible
        run: packer build .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
